appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: hkwc7J4Wdi/qsa9kEPrlqHSPM6TYnb/gtUxjKI3moqmvvZelbwtxCosDYzBB8dbD3d+QI6w11TGkGyb3zNYReVkKv/XTgkGTLZQkFzSly7Iti+BtJlEFwUGvjWvH3LcpbEOe3WhTOW1g7LfqNYYnZ6X/ONm29jbYRWh859l76DkDRFykyIGazmEMnig9vJEsOarwiDftv7PgefZg1jrF4xwYGipcQbekKG5/yUazwvBbSE0hvmJKI9a7XMwKg2k6bqPgHXpBFvR+Z+PRS2sJA+BmqRnyoAn/8fsr6gslkxcUfAKQMYaSTuRMsbtVGVJFao4rsulazXuBv7Efx0mQJYv+CWcR0X2Yo0o+5Tcm/jhoEpxY8If5GZLftzA5Vq/S4xLrQw11O7gky+bSsXBrYV40foBNrjMgSRsfh34FgkLWDHgUbnzkN+gh8g37GuwEs1Wz10W+dzM1CC+mFkjexssVInNj5c1OBdyliAMND/fSwqPxH8rlFvTqQVsehE1xzsallIdLnk8WBP09jo5zigM4jfixh63oPSaXD/1XV8sqIyudcLkdRzLlh/3PlYjpsXah0KGNGr1DAaXEFrqZeOwlyqVPuYJvU1aMUBuTUQESGS0OuwwBNCsDlUL3B4MC7/FX96ycigenmiQDXNxXbyCR+bXbLKdmYIIHbLRHfIU=
conda_forge_output_validation: false
