travis:
  secure:
    BINSTAR_TOKEN: qh6FNnRUvg+/6RG2Al0pLTkYX30j4qlJLmGHMeWHO1HP03nuhQKCtysd8hEsiw1j9IHadpwR4LL6k6imU8E05NNxWallSPAf053J2J+Tm1RWUSnyD+GZRA0kB+4ue/tmVf47ML3W97+PhJCCLneB2Epc7uKnnAXbLXOmQXmxp04FdmrG3CozoUpCs8A8I6OuApxmSi/C2WYnJGWgIfXP1IHgO0N6/eHLfQSUSBqJbUEStyUm0HoX3OkSH8t5NBZ3/Dys3T3GwPI6WnAt5JWXSwJehPIxkjtUXE6xuv77FLrQlvTWdsj6fw/XMlWedNUqLBRAOS5uNZMAMqTtm0KEYBai7E2AH3hTMcDL7o/QI7qMlfY7vRkCOGJRwBBIegSF6IvdxsKD19hx7jhokLfbUrHEYMFZs6gbAzwgd21tFWudby1hu1hxretGbOoDOXtNJLd76jxTv4W4HuqIcXyh09aRGU/7zYJDFYh67rv/ocwF/GNHZ1+P98HonS4Uqak4lU6kWz9Y7laFubP96NPBDkx5CEMYCtBOrA/AZn2aZ4EjvlDlCPN2AOUOYNx2GcQhwskOekL0cW9r4vAfRZDtaqpOr/g1cOcicUZAwUsT+YFrvfnONuYd/Ekc6JtcVlf9UiLLPLZtvDMt3iIftu53+/KeAcWPgWwIcpX2FHK1KTk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
